//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.lifeix.androidbasecoredemo.adapter;

import android.content.Context;

public final class ListViewAdapter_
    extends ListViewAdapter
{

    private Context context_;

    private ListViewAdapter_(Context context) {
        super(context);
        context_ = context;
        init_();
    }

    public static ListViewAdapter_ getInstance_(Context context) {
        return new ListViewAdapter_(context);
    }

    private void init_() {
        context = context_;
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
