//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.lifeix.androidbasecoredemo.service;

import android.content.Context;
import org.androidannotations.api.builder.ServiceIntentBuilder;

public final class DownloadService_
    extends DownloadService
{


    public static DownloadService_.IntentBuilder_ intent(Context context) {
        return new DownloadService_.IntentBuilder_(context);
    }

    public static class IntentBuilder_
        extends ServiceIntentBuilder<DownloadService_.IntentBuilder_>
    {


        public IntentBuilder_(Context context) {
            super(context, DownloadService_.class);
        }

    }

}
