//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.lifeix.androidbasecoredemo.service;

import android.content.Context;
import com.lifeix.androidbasecoredemo.DemoApplication_;
import org.androidannotations.api.builder.ServiceIntentBuilder;

public final class ReptileService_
    extends ReptileService
{


    public static ReptileService_.IntentBuilder_ intent(Context context) {
        return new ReptileService_.IntentBuilder_(context);
    }

    private void init_() {
        application = DemoApplication_.getInstance();
    }

    @Override
    public void onCreate() {
        init_();
        super.onCreate();
    }

    public static class IntentBuilder_
        extends ServiceIntentBuilder<ReptileService_.IntentBuilder_>
    {


        public IntentBuilder_(Context context) {
            super(context, ReptileService_.class);
        }

    }

}
