//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.lifeix.androidbasecoredemo.provider;


public final class PictureContentProvider_
    extends PictureContentProvider
{


}
