//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.lifeix.androidbasecoredemo.bean;

import android.app.Activity;
import android.app.Service;
import android.content.Context;
import android.util.Log;
import com.lifeix.androidbasecoredemo.MainActivity;

public final class User_
    extends User
{

    private Context context_;

    private User_(Context context) {
        context_ = context;
        init_();
    }

    public static User_ getInstance_(Context context) {
        return new User_(context);
    }

    private void init_() {
        if (context_ instanceof MainActivity) {
            myActivity = ((MainActivity) context_);
        } else {
            Log.w("User_", (("Due to Context class "+ context_.getClass().getSimpleName())+", the @RootContext MainActivity won't be populated"));
        }
        context = context_;
        if (context_ instanceof Activity) {
            activity = ((Activity) context_);
        } else {
            Log.w("User_", (("Due to Context class "+ context_.getClass().getSimpleName())+", the @RootContext Activity won't be populated"));
        }
        if (context_ instanceof Service) {
            service = ((Service) context_);
        } else {
            Log.w("User_", (("Due to Context class "+ context_.getClass().getSimpleName())+", the @RootContext Service won't be populated"));
        }
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
