//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.lifeix.androidbasecoredemo.broadcastreceiver;


public final class PushMsgBroadcastReceiver_
    extends PushMsgBroadcastReceiver
{


}
