//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.lifeix.androidbasecoredemo.view;

import android.content.Context;
import android.content.res.Resources;
import android.util.AttributeSet;
import com.lifeix.androidbasecoredemo.DemoApplication_;
import com.lifeix.androidbasecoredemo.R.string;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedNotifier;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class CustomButton_
    extends CustomButton
    implements HasViews
{

    private boolean alreadyInflated_ = false;
    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    public CustomButton_(Context context) {
        super(context);
        init_();
    }

    public CustomButton_(Context context, AttributeSet attrs) {
        super(context, attrs);
        init_();
    }

    public static CustomButton build(Context context) {
        CustomButton_ instance = new CustomButton_(context);
        instance.onFinishInflate();
        return instance;
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!alreadyInflated_) {
            alreadyInflated_ = true;
            onViewChangedNotifier_.notifyViewChanged(this);
        }
        super.onFinishInflate();
    }

    private void init_() {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        {
            Resources resources_ = getContext().getResources();
            defaultLabel = resources_.getString(string.app_name);
            application = DemoApplication_.getInstance();
        }
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public static CustomButton build(Context context, AttributeSet attrs) {
        CustomButton_ instance = new CustomButton_(context, attrs);
        instance.onFinishInflate();
        return instance;
    }

}
