//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.lifeix.androidbasecoredemo.view;

import android.content.Context;
import android.util.AttributeSet;
import android.widget.TextView;
import com.lifeix.androidbasecoredemo.R.id;
import com.lifeix.androidbasecoredemo.R.layout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class TitleWithSubtitle_
    extends TitleWithSubtitle
    implements HasViews, OnViewChangedListener
{

    private boolean alreadyInflated_ = false;
    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    public TitleWithSubtitle_(Context context) {
        super(context);
        init_();
    }

    public TitleWithSubtitle_(Context context, AttributeSet attrs) {
        super(context, attrs);
        init_();
    }

    public static TitleWithSubtitle build(Context context) {
        TitleWithSubtitle_ instance = new TitleWithSubtitle_(context);
        instance.onFinishInflate();
        return instance;
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!alreadyInflated_) {
            alreadyInflated_ = true;
            inflate(getContext(), layout.view_group_titlewithsub, this);
            onViewChangedNotifier_.notifyViewChanged(this);
        }
        super.onFinishInflate();
    }

    private void init_() {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public static TitleWithSubtitle build(Context context, AttributeSet attrs) {
        TitleWithSubtitle_ instance = new TitleWithSubtitle_(context, attrs);
        instance.onFinishInflate();
        return instance;
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        title = ((TextView) hasViews.findViewById(id.title));
        subtitle = ((TextView) hasViews.findViewById(id.subtitle));
    }

}
